### ISSUE TITLE
[Q] Compilation error

### ISSUE THREAD

**Issue by baerlein** [tsduck/tsduck#1615]
I followed the guide to compile on Ubuntu 22.04.05 but I'm getting errors:

```
make CC=gcc-13.3 NOTEST=1 NODEKTEC=1 NOHIDE=1 NOVATEK=1 NOOPENSSL=1 NOPCSC=1 NOSRT=1 NORIST=1
  [CXX] app/tsCommandLine.cpp
In file included from app/tsCommandLine.h:18,
                 from app/tsCommandLine.cpp:9:
app/tsEditLine.h:119:52: error: ‘maybe_unused’ attribute ignored [-Werror=attributes]
  119 |         [[maybe_unused]] bool    _update_history = false;
      |                                                    ^~~~~
app/tsEditLine.h:120:49: error: ‘maybe_unused’ attribute ignored [-Werror=attributes]
  120 |         [[maybe_unused]] UString _history_file {};
      |                                                 ^
app/tsEditLine.h:121:50: error: ‘maybe_unused’ attribute ignored [-Werror=attributes]
  121 |         [[maybe_unused]] size_t  _history_size = 0;
      |                                                  ^
cc1plus: all warnings being treated as errors
```

Any ideas how to solve this?

**Comment by baerlein** [comment]
@lelegard,

Now its working, thank you.
BTW, the reason I'm still using Ubuntu 22 is because I'm on WSL and haven't been able to upgrade it to 24.
