### ISSUE TITLE
Ubuntu *.deb issues (GLIBC)

### ISSUE THREAD

**Issue by dkashin** [tsduck/tsduck#125]
Hi @lelegard!
Thank you for the great app, it's really DVB rocket!

I've got some issues, so maybe you can share your thoughts here.

I took recent https://github.com/tsduck/tsduck/releases/download/v3.14-894/tsduck_3.14-894_amd64.deb and the installation was OK on my oldie Ubuntu 14.04.3 LTS and Ubuntu 16.04.1 LTS.

Next, both systems TSDuck was failed to run with the following:
`tsp: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version 'CURL_OPENSSL_4' not found (required by /usr/bin/tsduck.so)`
`tsp: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.27' not found (required by /usr/bin/tsduck.so)`

I google it and fond out that GLIBC_2.27 is the most recent core Unix C-Library provided in Ubuntu 18.XX version starting Feb 2018. Not sure about CURL_OPENSSL_4 but I guess the reason is the same.

I was wondering if you could please rebuild binaries inside of *.deb package with backward-compatibility of Ubuntu 14.04  (uses GLIBC_2.19) or Ubuntu 16.04  (uses GLIBC_2.23)

Thank you!

**Comment by lelegard** [comment]
Hello @dkashin,

The provided .deb packages are built on the latest Ubuntu version (18.04). I am not surprised if the libraries are not compatible in previous versions. I am just a bit surprised that the installation succeeded.

I currently provide binaries for the latest versions of Windows, Fedora, Ubuntu, Raspian and macOS. But, as a free open source maintainer, I do not have the resources to build on several older versions. But, like most open source projects, providing pre-built binaries is just a facility. Everyone is able to rebuild the binaries on any platform.

For TSDuck, this is explained [here](https://tsduck.io/doxy/building.html). You can download the source archive of the latest version [here](https://tsduck.io/download/source). In the case of Ubuntu 14 or 16, building the binary packages is as simple as:

```
sudo apt-get install g++ dpkg-dev doxygen dos2unix graphviz curl pcscd libpcsclite-dev libcppunit-dev libcurl3 libcurl3-dev
make deb
```

The first command installs the prerequisites, if not already done on your system. The second one builds the binaries.

**Comment by dkashin** [comment]
Thank you for fast reply!
Correct, I did everything you said with installing gcc/g++/curl elements from command above.
My config and output:

`Ubuntu 14.04.4 LTS (GNU/Linux 4.2.0-27-generic x86_64)`

`root@tc01:~/tsduck/tsduck-3.14-894# gcc -v`
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.1.0-5ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.1.0 (Ubuntu 8.1.0-5ubuntu1~14.04)`

Lots of errors and warnings.
Complete output of GCC: [tsduck_err.txt](https://github.com/tsduck/tsduck/files/2383054/tsduck_err.txt)

`root@tc01:~/tsduck/tsduck-3.14-894# sudo make`
`[CXX] tsPacketizer.cpp
In file included from tsEnumeration.h:36,
                 from tsMPEG.h:38,
                 from tsPacketizer.h:36,
                 from tsPacketizer.cpp:34:
tsUString.h: In member function 'std::basic_string<char16_t>::iterator ts::UString::erase(std::basic_string<char16_t>::const_iterator)':
tsUString.h:1799:84: error: no matching function for call to 'ts::UString::erase(std::basic_string<char16_t>::const_iterator&)'
         iterator erase(const_iterator position) { return SuperClass::erase(position); }
                                                                                                                            ^`
Please advise.

**Comment by lelegard** [comment]
Strange. How did you install gcc? Probably not using the standard Ubuntu repositories.

You have GCC 8.1.0 on Ubuntu 14.04.4 LTS while the standard GCC version is 4.8 for this Ubuntu (see [here](https://packages.ubuntu.com/trusty/devel/)).

The most recent Ubuntu (18.04.1 LTS) has GCC 7.3.0.

Note that TSDuck compiles fine with GCC 8.1 since Fedora 28 has GCC 8.1.1 and TSDuck works fine there.

The oldest GCC for which TSDuck is built is 4.8.5 on CentOS 7.5. 

Anyway, there is something unusual with your GCC installation on Ubuntu 14. I cannot answer this issue. But I suggest that you come back to a standard installation to make sure that everything is compatible: operating system, compiler and libraries.

**Comment by dkashin** [comment]
Yes it seems strange. I upgraded GCC from side official repository and it seems working good.
On Ubuntu 16.04 I have GCC 5.4.4 and TSDuck build was flawless. I guess I need to upgrade to Ubuntu 16.04+ anyway. Thank you for your help here! :)
