### ISSUE TITLE
Cannot build on Ubuntu 16.04

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#221]
encoder@hls1:~/src/tsduck$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Get this error
encoder@hls1:~/src/tsduck$ make
  [CXX] linux/tsTuner.cpp
linux/tsTuner.cpp: In member function ‘std::ostream& ts::Tuner::displayStatus(std::ostream&, const ts::UString&, ts::Report&)’:
linux/tsTuner.cpp:1424:67: error: cannot convert ‘ts::TunerParametersPtr {aka ts::SafePtr<ts::TunerParameters, ts::Mutex>}’ to ‘ts::TunerParameters*’ in initialization
     TunerParameters* params = TunerParameters::Factory(_tuner_type);
                                                                   ^
../../Makefile.common:898: recipe for target 'release-x86_64/tsTuner.o' failed
make[2]: *** [release-x86_64/tsTuner.o] Error 1

**Comment by lelegard** [comment]
Yes, sorry, a recent commit temporarily broke the compilation on Linux. Should be fixed with the last one.
